In [21]:
import pandas as pd
from functools import reduce
import glob
import os
import re

In [23]:
# import tables
# import spn_pbp_amr
resistance = pd.read_csv("../data_file/pathogenwatch_output20251221/spn_pbp_amr_use_this.csv")
# import serotype
serotype = pd.read_csv("../data_file/pathogenwatch_output20251221/serotype_use_this.csv")
# import mlst-pubmlst
mlst = pd.read_csv("../data_file/pathogenwatch_output20251221/mlst-pubmlst.csv")
# import metadata
metadata = pd.read_excel("../data_file/processed_clinical_data20260106_1.xlsx") # preprocessed manually
breakpoint = pd.read_excel("../data_file/Standard_breakpoint_table_for_SPN.xlsx") # not in use

In [25]:
# process metatable, for every MIC, consult the breakpoint table to obtain S/I/R to use for heatmap (done manually)
# for each sample, only keep accessionNum, fasta_id, antibiotics S/I/R
meta_col = ["accessionNum", "Genome Name", "Clinical Serotype", "Penicillin", "Penicillin_original", "pcn_sens_np",
            "Ceftriaxone", "Erythromycin", "Clindamycin", 
            "Vancomycin", "Tetracycline", "Levofloxacin", "NP swap/ear swap", "ageInMonths"]

select_meta = metadata[meta_col]

In [27]:
select_meta

,accessionNum,Genome Name,Clinical Serotype,Penicillin,Penicillin_original,pcn_sens_np,Ceftriaxone,Erythromycin,Clindamycin,Vancomycin,Tetracycline,Levofloxacin,NP swap/ear swap,ageInMonths
0,W17143487,2_S1_SPN,23B,S,S,Susceptible,S,S,S,S,S,S,NP,31
1,F16380623,3_S6_SPN,35B,I,I,Intermediate,S,R,S,S,S,S,NP,30
2,W17653277,4_S2_SPN,35B,I,I,Intermediate,S,R,S,S,S,S,NP,11
3,M17701635,5_S15_SPN,35B & 35D,S,I,Intermediate,S,R,S,S,S,S,NP,18
4,T18271326,6_S19_SPN,3,S,S,Susceptible,S,S,S,S,S,S,NP,29
5,M18434558,7_S13_SPN,17F,S,S,Susceptible,S,S,S,S,S,S,NP,12
6,F17654457,8_S30_SPN,17F,S,S,Susceptible,S,S,S,S,S,S,NP,6
7,F17896493,9_S33_SPN,17F,S,S,Susceptible,S,S,S,S,S,S,NP,30
8,F18239423,10_S22_SPN,35B,I,I,Intermediate,S,R,S,S,S,S,NP,22
9,T19376701,11_S7_SPN,3,S,S,Susceptible,S,R,R,S,R,S,NP,6
10,M19156630,12_S11_SPN,17F,S,S,Susceptible,S,S,S,S,S,S,NP,6
11,T19510623,13_S25_SPN,35B,I,I,Intermediate,S,R,S,S,S,S,NP,16
12,M19257038,14_S28_SPN,3,S,S,Susceptible,S,S,R,S,R,S,NP,22
13,F18448840,15_S31_SPN,11A,I,I,Intermediate,S,S,S,S,S,S,Ear,14
14,F18448806,16_S34_SPN,11A,I,I,Intermediate,S,S,S,S,S,S,NP,14
15,H19271491,17_S37_SPN,35B,I,I,Intermediate,S,R,S,S,S,S,NP,14
16,T19641883,18_S40_SPN,19F,S,S,Susceptible,S,S,S,S,S,S,NP,10
17,H19332824,19_S36_SPN,untypable,I,I,Intermediate,S,R,S,S,S,S,NP,23
18,T19860215,20_S3_SPN,35B,I,I,Intermediate,S,R,S,S,S,S,NP,18
19,W19724538,21_S39_SPN,35B,I,I,Intermediate,S,R,S,S,S,S,NP,20
20,W19756047,22_S8_SPN,17F,S,S,Susceptible,S,S,S,S,S,S,NP,18
21,W20312234,23_S12_SPN,35B,I,I,Intermediate,S,R,S,S,S,S,NP,18
22,M20130536,24_S16_SPN,35B,I,I,Intermediate,S,R,S,S,S,S,NP,21
23,H20143631,25_S17_SPN,19F,S,S,Susceptible,S,S,S,S,S,S,NP,9
24,H20175295,26_S23_SPN,19F,S,S,Susceptible,S,S,S,S,S,S,NP,8
25,T20595649,27_S42_SPN,17F,S,S,Susceptible,S,S,S,S,S,S,NP,21
26,H18637568,28_S5_SPN,35D,I,I,Intermediate,S,R,S,S,S,S,NP,15
27,H19691888,29_S20_SPN,35D,I,I,Intermediate,S,R,S,S,S,S,NP,18
28,H18510890,30_S26_SPN,35D,I,I,Intermediate,S,S,S,S,S,S,NP,23
29,M17945178,31_S10_SPN,35D,NaN,NaN,NaN,S,R,S,S,S,S,NP,15
30,F18442395,32_S29_SPN,35D,I,I,Intermediate,S,R,S,S,S,S,NP,17
31,M19219775,33_S32_SPN,35D,I,I,Intermediate,S,R,S,S,S,S,NP,8
32,T17202514,34_2_S35_SPN,15B,S,S,Susceptible,S,R,S,S,S,S,NP,10
33,M17112142,35_S38_SPN,15B,S,S,Susceptible,S,S,S,S,S,S,Ear,23
34,H17221555,36_S14_SPN,15B,S,S,Susceptible,S,S,S,S,S,S,NP,22
35,M18000909,37_S41_SPN,15B,S,S,Susceptible,S,R,S,S,S,S,NP,13
36,W18629076,38_S4_SPN,15B,S,S,Susceptible,S,S,S,S,S,S,NP,31
37,W18265095,39_S18_SPN,23B1,S,S,Susceptible,S,S,S,S,S,S,NP,8
38,H18485654,40_S9_SPN,23B1,I,I,Intermediate,S,S,S,S,S,S,NP,13
39,M18587789,41_S27_SPN,23B1,S,S,Susceptible,S,S,S,S,S,S,NP,11
40,M18617870,42_S21_SPN,23B1,I,I,Intermediate,S,S,S,S,S,S,NP,8

In [29]:
# process resistance table, rename to corresponding antibiotic
# for each sample, only keep Genome Name, antibiotic S/I/R
resist_col = ["Genome Name", 
              "amx", "croNonMeningitis", 
              "ctxNonMeningitis", "cxm", 
              "mem", "penNonMeningitis"]
select_resist = resistance[resist_col]

In [31]:
# process serotype table, keep only Genome Name and computed serotype
sero_col = ["Genome Name", "Serotype"]
select_patho_sero = serotype[sero_col]

In [33]:
# process mlst table, keep only Genome Name and ST
mlst_col = ["Genome Name", "ST"]
select_mlst = mlst[mlst_col]

In [35]:
# merge all tables based on Genome Name (fasta_id)
dfs = [
    select_meta, select_resist, select_patho_sero, select_mlst
]

merged = reduce(
    lambda left, right: pd.merge(left, right, on="Genome Name", how="left"),
    dfs
)

In [37]:
merged

,accessionNum,Genome Name,Clinical Serotype,Penicillin,Penicillin_original,pcn_sens_np,Ceftriaxone,Erythromycin,Clindamycin,Vancomycin,...,NP swap/ear swap,ageInMonths,amx,croNonMeningitis,ctxNonMeningitis,cxm,mem,penNonMeningitis,Serotype,ST
0,W17143487,2_S1_SPN,23B,S,S,Susceptible,S,S,S,S,...,NP,31,S,S,S,S,S,S,23B,1262
1,F16380623,3_S6_SPN,35B,I,I,Intermediate,S,R,S,S,...,NP,30,I,S,S,R,I,R,35B,558
2,W17653277,4_S2_SPN,35B,I,I,Intermediate,S,R,S,S,...,NP,11,NF,NaN,NaN,NaN,NF,NF,35B,37ba893024bc976f4b4de93628e4778e9a4726ca
3,M17701635,5_S15_SPN,35B & 35D,S,I,Intermediate,S,R,S,S,...,NP,18,I,S,S,R,I,R,35B,dbf4e9531e53ffa309916adceab4f755649143ce
4,T18271326,6_S19_SPN,3,S,S,Susceptible,S,S,S,S,...,NP,29,S,S,S,S,S,S,03,180
5,M18434558,7_S13_SPN,17F,S,S,Susceptible,S,S,S,S,...,NP,12,S,S,S,S,S,S,17F,392
6,F17654457,8_S30_SPN,17F,S,S,Susceptible,S,S,S,S,...,NP,6,S,S,S,S,S,S,17F,392
7,F17896493,9_S33_SPN,17F,S,S,Susceptible,S,S,S,S,...,NP,30,S,S,S,S,S,S,17F,392
8,F18239423,10_S22_SPN,35B,I,I,Intermediate,S,R,S,S,...,NP,22,I,S,S,R,I,R,35B,156
9,T19376701,11_S7_SPN,3,S,S,Susceptible,S,R,R,S,...,NP,6,S,S,S,S,S,S,03,180
10,M19156630,12_S11_SPN,17F,S,S,Susceptible,S,S,S,S,...,NP,6,S,S,S,S,S,S,17F,392
11,T19510623,13_S25_SPN,35B,I,I,Intermediate,S,R,S,S,...,NP,16,I,S,S,R,I,R,35B,156
12,M19257038,14_S28_SPN,3,S,S,Susceptible,S,S,R,S,...,NP,22,S,S,S,S,S,S,03,180
13,F18448840,15_S31_SPN,11A,I,I,Intermediate,S,S,S,S,...,Ear,14,S,S,S,S,S,I,11A,156
14,F18448806,16_S34_SPN,11A,I,I,Intermediate,S,S,S,S,...,NP,14,S,S,S,S,S,I,11A,156
15,H19271491,17_S37_SPN,35B,I,I,Intermediate,S,R,S,S,...,NP,14,I,S,S,R,I,R,35B,10493
16,T19641883,18_S40_SPN,19F,S,S,Susceptible,S,S,S,S,...,NP,10,S,S,S,S,S,S,19F,c3a49cce5979a37288a19c47ac50cf60e0f3fd7b
17,H19332824,19_S36_SPN,untypable,I,I,Intermediate,S,R,S,S,...,NP,23,R,S,S,R,R,R,untypable,15a3c3770c797dc051a6718a2bf17301575d10c1
18,T19860215,20_S3_SPN,35B,I,I,Intermediate,S,R,S,S,...,NP,18,I,S,S,R,I,R,35B,156
19,W19724538,21_S39_SPN,35B,I,I,Intermediate,S,R,S,S,...,NP,20,I,S,S,R,I,R,35B,10493
20,W19756047,22_S8_SPN,17F,S,S,Susceptible,S,S,S,S,...,NP,18,S,S,S,S,S,S,17F,392
21,W20312234,23_S12_SPN,35B,I,I,Intermediate,S,R,S,S,...,NP,18,I,S,S,R,I,R,35B,156
22,M20130536,24_S16_SPN,35B,I,I,Intermediate,S,R,S,S,...,NP,21,I,S,S,R,I,R,35B,156
23,H20143631,25_S17_SPN,19F,S,S,Susceptible,S,S,S,S,...,NP,9,S,S,S,S,S,S,19F,654
24,H20175295,26_S23_SPN,19F,S,S,Susceptible,S,S,S,S,...,NP,8,I,S,S,R,I,R,35B,558
25,T20595649,27_S42_SPN,17F,S,S,Susceptible,S,S,S,S,...,NP,21,S,S,S,S,S,S,17F,1924
26,H18637568,28_S5_SPN,35D,I,I,Intermediate,S,R,S,S,...,NP,15,I,S,S,R,I,R,35B,10493
27,H19691888,29_S20_SPN,35D,I,I,Intermediate,S,R,S,S,...,NP,18,I,S,S,R,I,R,35B,156
28,H18510890,30_S26_SPN,35D,I,I,Intermediate,S,S,S,S,...,NP,23,I,S,S,R,I,R,35B,156
29,M17945178,31_S10_SPN,35D,NaN,NaN,NaN,S,R,S,S,...,NP,15,R,S,S,R,R,R,35B,ca9c271b9ef8eca2d633a6f8ec19b509aa557e38
30,F18442395,32_S29_SPN,35D,I,I,Intermediate,S,R,S,S,...,NP,17,I,S,S,R,I,R,35B,156
31,M19219775,33_S32_SPN,35D,I,I,Intermediate,S,R,S,S,...,NP,8,S,S,S,S,S,S,19F,654
32,T17202514,34_2_S35_SPN,15B,S,S,Susceptible,S,R,S,S,...,NP,10,S,S,S,S,S,S,15B,1262
33,M17112142,35_S38_SPN,15B,S,S,Susceptible,S,S,S,S,...,Ear,23,S,S,S,S,S,S,15B,1757
34,H17221555,36_S14_SPN,15B,S,S,Susceptible,S,S,S,S,...,NP,22,S,S,S,S,S,S,15B,1262
35,M18000909,37_S41_SPN,15B,S,S,Susceptible,S,R,S,S,...,NP,13,S,S,S,S,S,S,15B,1262
36,W18629076,38_S4_SPN,15B,S,S,Susceptible,S,S,S,S,...,NP,31,S,S,S,S,S,S,15B,1262
37,W18265095,39_S18_SPN,23B1,S,S,Susceptible,S,S,S,S,...,NP,8,S,S,S,S,S,S,23B,36
38,H18485654,40_S9_SPN,23B1,I,I,Intermediate,S,S,S,S,...,NP,13,S,S,S,S,S,I,23B,1373
39,M18587789,41_S27_SPN,23B1,S,S,Susceptible,S,S,S,S,...,NP,11,S,S,S,S,S,S,23B,36
40,M18617870,42_S21_SPN,23B1,I,I,Intermediate,S,S,S,S,...,NP,8,S,S,S,S,S,S,23B,14492

In [39]:
merged.to_csv("merged_table_20260106.csv", index=False)