In [1]:
import pandas as pd
import glob
import os
import re

In [3]:
# import file
df = pd.read_excel("../data_file/TAP metadata366 Oct2025 for canada_withedit.xlsx")
# use to map accession to file name
map_table = pd.read_excel("../data_file/Look_up_table.xlsx")
# loading fast names
fasta_files = glob.glob("../Assembly/kraken_purifyed_illumina/*_SPN.fasta")

In [5]:
# define target columns
# included PCN, Ceftriaxone*, Erythromycin*, Clindamycin*, Vancomycin, Tetracycline*, Levofloxacin
# unit: (mcg/mL)
cols = [
    "accessionNum", "spn_sero",
    
    "pcnmic_pre_np", "pcnmic_np",
    
    "cefmic_pre_np", "cefmic_np",
    
    "erythmic_pre_np", "erythmic_np",
    "clindamic_pre_np", "clindamic_np",
    "amoxmic_pre_np", "amoxmic_np",
    "methomic_pre_np", "methomic_np",
    "levomic_pre_np", "levomic_np",
    "pcn_sens_np",
    "pcnmic_pre_ear", "pcnmic_ear",
    "cefmic_pre_ear", "cefmic_ear",
    "erythmic_pre_ear", "erythmic_ear",
    "clindamic_pre_ear", "clindamic_ear",
    "amoxmic_pre_ear", "amoxmic_ear",
    "methomic_pre_ear", "methomic_ear",
    "levomic_pre_ear", "levomic_ear",
    "pcn_sens_ear", "ageInMonths",
]

# obtain a table with sub-column
df_sub = df[cols]

In [7]:
# select target samples
target_accessions = ["W17143487", "F16380623", "W17653277", "M17701635", "T18271326", "M18434558", "F17654457", "F17896493",
    "F18239423", "T19376701", "M19156630", "T19510623", "M19257038", "F18448840", "F18448806", "H19271491",
    "T19641883", "H19332824", "T19860215", "W19724538", "W19756047", "W20312234", "M20130536", "H20143631",
    "H20175295", "T20595649", "H18637568", "H19691888", "H18510890", "M17945178", "F18442395", "M19219775",
    "T17202514", "M17112142", "H17221555", "M18000909", "W18629076", "W18265095", "H18485654", "M18587789",
    "M18617870",
]

# obtain target rows
df_filtered = df_sub[df_sub["accessionNum"].isin(target_accessions)]

In [9]:
df_filtered

,accessionNum,spn_sero,pcnmic_pre_np,pcnmic_np,cefmic_pre_np,cefmic_np,erythmic_pre_np,erythmic_np,clindamic_pre_np,clindamic_np,...,clindamic_pre_ear,clindamic_ear,amoxmic_pre_ear,amoxmic_ear,methomic_pre_ear,methomic_ear,levomic_pre_ear,levomic_ear,pcn_sens_ear,ageInMonths
76,T17202514,15B,<=,0.06,<=,0.12,=,1.00,<=,0.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
78,W17143487,23B,<=,0.06,<=,0.12,<=,0.12,<=,0.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
80,F16380623,35B,=,1.00,=,0.50,>=,8.00,<=,0.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30
82,M17112142,15B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,<=,0.25,=,0.5,<=,0.25,=,1.0,Susceptible,23
83,H17221555,15B,<=,0.06,<=,0.12,<=,0.12,<=,0.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22
87,W17653277,35B,=,1.00,=,1.00,>=,8.00,<=,0.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11
90,M17701635,35B (batch 1) & 35D (batch 4),=,0.50,=,0.25,>=,8.00,<=,0.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18
93,M17945178,35D,NaN,NaN,=,1.00,>=,8.00,<=,0.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15
96,M18000909,15B,<=,0.06,<=,0.12,>=,8.00,<=,0.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
97,T18271326,3,<=,0.06,<=,0.12,<=,0.12,<=,0.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29
99,W18265095,23B1,<=,0.06,<=,0.12,<=,0.12,<=,0.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8
108,M18434558,17F,<=,0.06,<=,0.12,<=,0.12,<=,0.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12
109,F17654457,17F,<=,0.06,<=,0.12,<=,0.12,<=,0.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6
110,W18629076,15B,<=,0.06,<=,0.12,<=,0.12,<=,0.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
111,H18485654,23B1,=,0.25,<=,0.12,<=,0.12,<=,0.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
115,H18510890,35D,=,1.00,=,0.50,<=,0.12,<=,0.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23
118,M18587789,23B1,<=,0.06,<=,0.12,<=,0.12,<=,0.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11
126,M18617870,23B1,=,0.25,<=,0.12,<=,0.12,<=,0.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8
135,H18637568,35D,=,1.00,=,1.00,=,4.00,<=,0.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15
138,F17896493,17F,<=,0.06,<=,0.12,<=,0.12,<=,0.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30
167,F18239423,35B,=,1.00,=,1.00,>=,8.00,<=,0.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22
168,T19376701,3,<=,0.06,<=,0.12,=,22.00,>=,1.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6
176,M19156630,17F,<=,0.06,<=,0.12,<=,0.12,<=,0.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6
180,T19510623,35B,=,1.00,=,1.00,>=,8.00,<=,0.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16
184,M19219775,35D,=,1.00,=,1.00,>=,8.00,<=,0.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8
191,M19257038,3,=,0.03,<=,0.12,<=,0.12,>=,1.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22
195,F18442395,35D,=,1.00,=,1.00,>=,8.00,<=,0.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
198,F18448806,11A,=,0.25,=,0.25,<=,0.12,<=,0.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14
199,F18448840,11A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,<=,0.25,=,0.5,<=,0.25,=,1.0,Intermediate,14
202,H19271491,35B,=,1.00,=,1.00,=,4.00,<=,0.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14
203,T19641883,19F,<=,0.06,<=,0.12,<=,0.12,<=,0.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
209,H19332824,untypable,=,0.25,=,0.25,=,4.00,<=,0.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23
228,T19860215,35B,=,1.00,=,1.00,>=,8.00,<=,0.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18
232,W19724538,35B,=,1.00,=,1.00,>=,8.00,<=,0.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20
235,W19756047,17F,<=,0.06,<=,0.12,<=,0.12,<=,0.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18
246,H19691888,35D,=,1.00,=,1.00,>=,8.00,<=,0.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18
292,W20312234,35B,=,1.00,=,1.00,>=,8.00,<=,0.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18
294,M20130536,35B,=,1.00,=,1.00,>=,8.00,<=,0.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21
298,H20143631,19F,<=,0.06,<=,0.12,<=,0.12,<=,0.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
303,H20175295,19F,<=,0.06,<=,0.12,<=,0.12,<=,0.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8
313,T20595649,17F,<=,0.06,<=,0.12,<=,0.12,<=,0.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21

In [13]:
# use to build join table 
# Build a dict[ our_number : filename ]
num_to_id = {}
for f in fasta_files:
    # obtain file
    fname = os.path.basename(f)
    # if file is target (according to regex)
    m = re.match(r"^(\d+)_.*_SPN\.fasta$", fname)
    if m:
        # obtain internal id
        our_num = int(m.group(1))
        fasta_id = os.path.splitext(fname)[0]
        num_to_id[our_num] = fasta_id

map_table["fasta_id"] = map_table["Our number"].map(num_to_id)
#map_table.to_excel("../data_file/map_id_fasta.xlsx", index=False)

In [15]:
map_table

   Accession No  Column1  Our number have data found on table      fasta_id
0     W15810037      NaN           1       NaN            NaN           NaN
1     W17143487      NaN           2         x              x      2_S1_SPN
2     F16380623      NaN           3         x              x      3_S6_SPN
3     W17653277      NaN           4         x              x      4_S2_SPN
4     M17701635      NaN           5         x              x     5_S15_SPN
5     T18271326      NaN           6         x              x     6_S19_SPN
6     M18434558      NaN           7         x              x     7_S13_SPN
7     F17654457      NaN           8         x              x     8_S30_SPN
8     F17896493      NaN           9         x              x     9_S33_SPN
9     F18239423      NaN          10         x              x    10_S22_SPN
10    T19376701      NaN          11         x              x     11_S7_SPN
11    M19156630      NaN          12         x              x    12_S11_SPN
12    T19510623      NaN          13         x              x    13_S25_SPN
13    M19257038      NaN          14         x              x    14_S28_SPN
14    F18448840      NaN          15         x              x    15_S31_SPN
15    F18448806      NaN          16         x              x    16_S34_SPN
16    H19271491      NaN          17         x              x    17_S37_SPN
17    T19641883      NaN          18         x              x    18_S40_SPN
18    H19332824      NaN          19         x              x    19_S36_SPN
19    T19860215      NaN          20         x              x     20_S3_SPN
20    W19724538      NaN          21         x              x    21_S39_SPN
21    W19756047      NaN          22         x              x     22_S8_SPN
22    W20312234      NaN          23         x              x    23_S12_SPN
23    M20130536      NaN          24         x              x    24_S16_SPN
24    H20143631      NaN          25         x              x    25_S17_SPN
25    H20175295      NaN          26         x              x    26_S23_SPN
26    T20595649      NaN          27         x              x    27_S42_SPN
27    H18637568      NaN          28         x              x     28_S5_SPN
28    H19691888      NaN          29         x              x    29_S20_SPN
29    H18510890      NaN          30         x              x    30_S26_SPN
30    M17945178      NaN          31         x              x    31_S10_SPN
31    F18442395      NaN          32         x              x    32_S29_SPN
32    M19219775      NaN          33         x              x    33_S32_SPN
33    T17202514      NaN          34         x              x  34_2_S35_SPN
34    M17112142      NaN          35         x              x    35_S38_SPN
35    H17221555      NaN          36         x              x    36_S14_SPN
36    M18000909      NaN          37         x              x    37_S41_SPN
37    W18629076      NaN          38         x              x     38_S4_SPN
38    W18265095      NaN          39         x              x    39_S18_SPN
39    H18485654      NaN          40         x              x     40_S9_SPN
40    M18587789      NaN          41         x              x    41_S27_SPN
41    M18617870      NaN          42         x              x    42_S21_SPN
42    H19207745      NaN          43       NaN            NaN           NaN

In [17]:
map_table_filtered = map_table.drop(columns=["Our number", "Column1", "have data", "found on table"])
map_table_filtered = map_table_filtered.rename(columns={"Accession No": "accessionNum"})

In [19]:
map_table_filtered

   accessionNum      fasta_id
0     W15810037           NaN
1     W17143487      2_S1_SPN
2     F16380623      3_S6_SPN
3     W17653277      4_S2_SPN
4     M17701635     5_S15_SPN
5     T18271326     6_S19_SPN
6     M18434558     7_S13_SPN
7     F17654457     8_S30_SPN
8     F17896493     9_S33_SPN
9     F18239423    10_S22_SPN
10    T19376701     11_S7_SPN
11    M19156630    12_S11_SPN
12    T19510623    13_S25_SPN
13    M19257038    14_S28_SPN
14    F18448840    15_S31_SPN
15    F18448806    16_S34_SPN
16    H19271491    17_S37_SPN
17    T19641883    18_S40_SPN
18    H19332824    19_S36_SPN
19    T19860215     20_S3_SPN
20    W19724538    21_S39_SPN
21    W19756047     22_S8_SPN
22    W20312234    23_S12_SPN
23    M20130536    24_S16_SPN
24    H20143631    25_S17_SPN
25    H20175295    26_S23_SPN
26    T20595649    27_S42_SPN
27    H18637568     28_S5_SPN
28    H19691888    29_S20_SPN
29    H18510890    30_S26_SPN
30    M17945178    31_S10_SPN
31    F18442395    32_S29_SPN
32    M19219775    33_S32_SPN
33    T17202514  34_2_S35_SPN
34    M17112142    35_S38_SPN
35    H17221555    36_S14_SPN
36    M18000909    37_S41_SPN
37    W18629076     38_S4_SPN
38    W18265095    39_S18_SPN
39    H18485654     40_S9_SPN
40    M18587789    41_S27_SPN
41    M18617870    42_S21_SPN
42    H19207745           NaN

In [21]:
merge_clinical = pd.merge(map_table_filtered, df_filtered, on="accessionNum", how="inner")

In [23]:
merge_clinical

,accessionNum,fasta_id,spn_sero,pcnmic_pre_np,pcnmic_np,cefmic_pre_np,cefmic_np,erythmic_pre_np,erythmic_np,clindamic_pre_np,...,clindamic_pre_ear,clindamic_ear,amoxmic_pre_ear,amoxmic_ear,methomic_pre_ear,methomic_ear,levomic_pre_ear,levomic_ear,pcn_sens_ear,ageInMonths
0,W17143487,2_S1_SPN,23B,<=,0.06,<=,0.12,<=,0.12,<=,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
1,F16380623,3_S6_SPN,35B,=,1.00,=,0.50,>=,8.00,<=,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30
2,W17653277,4_S2_SPN,35B,=,1.00,=,1.00,>=,8.00,<=,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11
3,M17701635,5_S15_SPN,35B (batch 1) & 35D (batch 4),=,0.50,=,0.25,>=,8.00,<=,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18
4,T18271326,6_S19_SPN,3,<=,0.06,<=,0.12,<=,0.12,<=,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29
5,M18434558,7_S13_SPN,17F,<=,0.06,<=,0.12,<=,0.12,<=,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12
6,F17654457,8_S30_SPN,17F,<=,0.06,<=,0.12,<=,0.12,<=,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6
7,F17896493,9_S33_SPN,17F,<=,0.06,<=,0.12,<=,0.12,<=,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30
8,F18239423,10_S22_SPN,35B,=,1.00,=,1.00,>=,8.00,<=,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22
9,T19376701,11_S7_SPN,3,<=,0.06,<=,0.12,=,22.00,>=,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6
10,M19156630,12_S11_SPN,17F,<=,0.06,<=,0.12,<=,0.12,<=,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6
11,T19510623,13_S25_SPN,35B,=,1.00,=,1.00,>=,8.00,<=,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16
12,M19257038,14_S28_SPN,3,=,0.03,<=,0.12,<=,0.12,>=,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22
13,F18448840,15_S31_SPN,11A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,<=,0.25,=,0.5,<=,0.25,=,1.0,Intermediate,14
14,F18448806,16_S34_SPN,11A,=,0.25,=,0.25,<=,0.12,<=,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14
15,H19271491,17_S37_SPN,35B,=,1.00,=,1.00,=,4.00,<=,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14
16,T19641883,18_S40_SPN,19F,<=,0.06,<=,0.12,<=,0.12,<=,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
17,H19332824,19_S36_SPN,untypable,=,0.25,=,0.25,=,4.00,<=,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23
18,T19860215,20_S3_SPN,35B,=,1.00,=,1.00,>=,8.00,<=,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18
19,W19724538,21_S39_SPN,35B,=,1.00,=,1.00,>=,8.00,<=,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20
20,W19756047,22_S8_SPN,17F,<=,0.06,<=,0.12,<=,0.12,<=,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18
21,W20312234,23_S12_SPN,35B,=,1.00,=,1.00,>=,8.00,<=,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18
22,M20130536,24_S16_SPN,35B,=,1.00,=,1.00,>=,8.00,<=,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21
23,H20143631,25_S17_SPN,19F,<=,0.06,<=,0.12,<=,0.12,<=,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
24,H20175295,26_S23_SPN,19F,<=,0.06,<=,0.12,<=,0.12,<=,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8
25,T20595649,27_S42_SPN,17F,<=,0.06,<=,0.12,<=,0.12,<=,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21
26,H18637568,28_S5_SPN,35D,=,1.00,=,1.00,=,4.00,<=,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15
27,H19691888,29_S20_SPN,35D,=,1.00,=,1.00,>=,8.00,<=,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18
28,H18510890,30_S26_SPN,35D,=,1.00,=,0.50,<=,0.12,<=,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23
29,M17945178,31_S10_SPN,35D,NaN,NaN,=,1.00,>=,8.00,<=,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15
30,F18442395,32_S29_SPN,35D,=,1.00,=,1.00,>=,8.00,<=,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
31,M19219775,33_S32_SPN,35D,=,1.00,=,1.00,>=,8.00,<=,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8
32,T17202514,34_2_S35_SPN,15B,<=,0.06,<=,0.12,=,1.00,<=,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
33,M17112142,35_S38_SPN,15B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,<=,0.25,=,0.5,<=,0.25,=,1.0,Susceptible,23
34,H17221555,36_S14_SPN,15B,<=,0.06,<=,0.12,<=,0.12,<=,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22
35,M18000909,37_S41_SPN,15B,<=,0.06,<=,0.12,>=,8.00,<=,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
36,W18629076,38_S4_SPN,15B,<=,0.06,<=,0.12,<=,0.12,<=,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
37,W18265095,39_S18_SPN,23B1,<=,0.06,<=,0.12,<=,0.12,<=,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8
38,H18485654,40_S9_SPN,23B1,=,0.25,<=,0.12,<=,0.12,<=,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
39,M18587789,41_S27_SPN,23B1,<=,0.06,<=,0.12,<=,0.12,<=,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11
40,M18617870,42_S21_SPN,23B1,=,0.25,<=,0.12,<=,0.12,<=,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8

In [25]:
merge_clinical.to_excel("../data_file/processed_clinical_data_20260106.xlsx", index=False)