In [1]:
import pandas as pd
import numpy as np
from functools import reduce
from pathlib import Path
import glob
import os
import re

In [25]:
# requirement:
# all pathogenwatch outputs under the same directory
# checkm quality file place under pathogenwatch output directory
# a .tree file for corresponding pathogenwatch output
# a metadata files thats preprocessed

In [3]:
# import tables
# set pathogenwatch directory
#DIR = Path(r"C:/Users/Amoeb/Documents/ZSW2025-2026/Waterloo_courses/BIOL499A/nanopore/nanopore_racon_medaka/kraken_contig_result/Pathogenwatch/")
DIR = Path(r"C:/Users/Amoeb/Documents/ZSW2025-2026/Waterloo_courses/BIOL499A/nanopore/nanopore_medaka_polypolisher_pypolca/tree_output/")

CHECKM_file = "racon_medaka_quality_report.tsv"
OUTPUT_file = "ready_for_R_plot_final.csv"
# set regex for id/Genome Name
pattern = r'(.+?)_nanopore'

In [29]:
# import spn_pbp_amr, extract index, keep only needed columns
resistance = pd.read_csv(DIR / "spn_pbp_amr.csv")
resistance["Index"] = resistance["Genome Name"].str.extract(pattern)  # edit regex if needed

# readjust the pathogenwatch result by CLSI strandard Threshold
def extract_mic(val):
    if pd.isna(val):
        return np.nan
    val = str(val)
    match = re.search(r'[\d\.]+', val)
    return float(match.group()) if match else np.nan

mic_cols = ["amxMic", "croMic", "ctxMic", "memMic", "penMic"]
for col in mic_cols:
    resistance[col + "_num"] = resistance[col].apply(extract_mic)

# I typed it manually here, but actual data exist in MIC_TABLE_FINAL.xlsx
antibiotics = {
    "amxMic_num": {
        "name": "Amoxicillin",
        "bp": {"S": 2, "I": 4, "R": 8}},
    "croMic_num": {
        "name": "Ceftriaxone",
        "bp": {"S": 1, "I": 2, "R": 4}},
    "ctxMic_num": {
        "name": "Cefotaxime",
        "bp": {"S": 1, "I": 2, "R": 4}},
    "memMic_num": {
        "name": "Meropenem",
        "bp": {"S": 0.25, "I": 0.5, "R": 1}},
    "penMic_num": {
        "name": "Penicillin",
        "bp": {"S": 0.06, "I_low": 0.12, "I_high": 1, "R": 2}}
}

# sorry for my ugly code... Classify the S/I/R base of CLSI breakpoint
def classify_mic(val, bp):
    if pd.isna(val):
        return np.nan
    if "I_low" in bp:   # penicillin have upper and lower
        if val <= bp["S"]:
            return "S"
        elif bp["I_low"] <= val <= bp["I_high"]:
            return "I"
        elif val >= bp["R"]:
            return "R"
    else:
        if val <= bp["S"]:
            return "S"
        elif val == bp["I"]:
            return "I"
        elif val >= bp["R"]:
            return "R"
    return np.nan

for mic_col, info in antibiotics.items():
    antibiotic_name = info["name"]
    bp = info["bp"]
    new_col = antibiotic_name + "_adjusted"
    resistance[new_col] = resistance[mic_col].apply(
        lambda x: classify_mic(x, bp)
    )

cols_keep = [
    "Index",
    "Amoxicillin_adjusted",
    "Ceftriaxone_adjusted",
    "Cefotaxime_adjusted",
    "Meropenem_adjusted",
    "Penicillin_adjusted"
]

select_resist = resistance[cols_keep]

In [31]:
# import serotype, extract index, keep only needed columns
serotype = pd.read_csv(DIR / "serotype.csv")
serotype["Index"] = serotype["Genome Name"].str.extract(pattern)  # edit regex if needed
select_serotype = serotype[["Index", "Serotype"]]

In [33]:
# import mlst-pubmlst, extract index, keep only needed columns. 
# for ST that's longer than 10 string, reduce to 4, and add * in front
mlst = pd.read_csv(DIR / "mlst-pubmlst.csv")
mlst["Index"] = mlst["Genome Name"].str.extract(pattern)  # edit regex if needed
select_mlst = mlst[["Index", "ST"]]
mask = select_mlst["ST"].str.len() > 10
select_mlst.loc[mask, "ST"] = "*" + select_mlst.loc[mask, "ST"].str[:4]
select_mlst = select_mlst.rename(columns={"ST": "mlst"})

In [35]:
# a spot for genome completion from checkm or braken
checkm = pd.read_csv(DIR / CHECKM_file, delimiter='\t')
checkm["Index"] = checkm["Name"].str.extract(pattern)
selected_checkm = checkm[["Index", "Completeness"]]
selected_checkm = selected_checkm.rename(columns={"Completeness": "Genome_Completeness"})

In [37]:
selected_checkm

                    Index  Genome_Completeness
0        i10_02_barcode11                99.99
1        i11_03_barcode74                98.65
2        i12_02_barcode35               100.00
3        i13_02_barcode17                99.99
4        i14_02_barcode41               100.00
5        i15_02_barcode09                99.99
6        i16_02_barcode57               100.00
7        i17_02_barcode51               100.00
8        i18_03_barcode91                86.20
9        i19_03_barcode20                91.21
10       i20_02_barcode12                99.99
11       i21_02_barcode28               100.00
12       i22_03_barcode13                88.68
13       i23_02_barcode58                99.99
14       i24_02_barcode74                99.94
15       i25_04_barcode53                84.89
16       i26_04_barcode14                83.43
17       i27_04_barcode78                86.32
18       i28_03_barcode17                99.76
19       i29_03_barcode37                99.81
20        i2_01_barcode03                99.99
21       i30_03_barcode58                91.21
22       i31_03_barcode73                92.19
23       i32_03_barcode76                95.27
24       i33_03_barcode90                99.18
25       i34_03_barcode33                96.15
26       i35_03_barcode41                97.56
27       i36_03_barcode49                93.94
28       i37_03_barcode09                90.77
29       i38_01_barcode36                99.87
30       i39_01_barcode24               100.00
31        i3_01_barcode05               100.00
32       i40_01_barcode37                99.99
33       i41_01_barcode39               100.00
34       i42_01_barcode40                99.99
35        i4_01_barcode11                99.99
36  i5_01_04_barcode12_33                99.75
37        i6_02_barcode90               100.00
38        i7_01_barcode34               100.00
39        i8_01_barcode35               100.00
40        i9_03_barcode89                96.44

In [39]:
# import metadata and add files label (using this same metadata here)
metadata = pd.read_csv("../nanopore/metadata_20260212.csv") # preprocessed manually
mapdata = pd.read_excel("../nanopore/illumina_nanopore_mapping.xlsx") # preprocessed with another script
indexed_metadata = mapdata.merge(metadata, on="accessionNum", how="left")

In [41]:
# merge all tables based on index
meta_pathogen_merged = (
    indexed_metadata
    .merge(select_resist,   on="Index", how="left")
    .merge(select_serotype, on="Index", how="left")
    .merge(select_mlst,     on="Index", how="left")
    .merge(selected_checkm, on="Index", how="left")
)

In [43]:
meta_pathogen_merged

,accessionNum,Index,Penicillin,Ceftriaxone,Erythromycin,Clindamycin,Vancomycin,Tetracycline,Levofloxacin,NP swap/ear swap,ageInMonths,Amoxicillin_adjusted,Ceftriaxone_adjusted,Cefotaxime_adjusted,Meropenem_adjusted,Penicillin_adjusted,Serotype,mlst,Genome_Completeness
0,W17143487,i2_01_barcode03,S,S,S,S,S,S,S,NP,31,S,S,S,S,S,23B,1262,99.99
1,F16380623,i3_01_barcode05,I,S,R,S,S,S,S,NP,30,I,S,S,I,R,35B,558,100.00
2,W17653277,i4_01_barcode11,I,S,R,S,S,S,S,NP,11,S,S,S,I,R,35B,*e0a6,99.99
3,M17701635,i5_01_04_barcode12_33,S,S,R,S,S,S,S,NP,18,I,S,S,I,R,35B,*dbf4,99.75
4,T18271326,i6_02_barcode90,S,S,S,S,S,S,S,NP,29,S,S,S,S,S,03,180,100.00
5,M18434558,i7_01_barcode34,S,S,S,S,S,S,S,NP,12,S,S,S,S,S,17F,392,100.00
6,F17654457,i8_01_barcode35,S,S,S,S,S,S,S,NP,6,S,S,S,S,S,17F,392,100.00
7,F17896493,i9_03_barcode89,S,S,S,S,S,S,S,NP,30,S,S,S,S,S,17F,*3daf,96.44
8,F18239423,i10_02_barcode11,I,S,R,S,S,S,S,NP,22,S,S,S,S,I,35B,156,99.99
9,T19376701,i11_03_barcode74,S,S,R,R,S,R,S,NP,6,NaN,NaN,NaN,NaN,NaN,03,*4f1d,98.65
10,M19156630,i12_02_barcode35,S,S,S,S,S,S,S,NP,6,S,S,S,S,S,17F,392,100.00
11,T19510623,i13_02_barcode17,I,S,R,S,S,S,S,NP,16,I,S,S,I,R,35B,156,99.99
12,M19257038,i14_02_barcode41,S,S,S,R,S,R,S,NP,22,S,S,S,S,S,03,180,100.00
13,F18448840,i15_02_barcode09,I,S,S,S,S,S,S,Ear,14,S,S,S,S,I,11A,156,99.99
14,F18448806,i16_02_barcode57,I,S,S,S,S,S,S,NP,14,S,S,S,S,I,11A,156,100.00
15,H19271491,i17_02_barcode51,I,S,R,S,S,S,S,NP,14,I,S,S,I,R,35B,10493,100.00
16,T19641883,i18_03_barcode91,S,S,S,S,S,S,S,NP,10,S,S,S,S,S,19F,*b064,86.20
17,H19332824,i19_03_barcode20,I,S,R,S,S,S,S,NP,23,S,S,S,S,I,untypable,*611e,91.21
18,T19860215,i20_02_barcode12,I,S,R,S,S,S,S,NP,18,I,S,S,I,R,35B,156,99.99
19,W19724538,i21_02_barcode28,I,S,R,S,S,S,S,NP,20,I,S,S,I,R,35B,10493,100.00
20,W19756047,i22_03_barcode13,S,S,S,S,S,S,S,NP,18,S,S,S,S,I,17F,*f0e6,88.68
21,W20312234,i23_02_barcode58,I,S,R,S,S,S,S,NP,18,I,S,S,I,R,35B,156,99.99
22,M20130536,i24_02_barcode74,I,S,R,S,S,S,S,NP,21,I,S,S,I,R,35B,156,99.94
23,H20143631,i25_04_barcode53,S,S,S,S,S,S,S,NP,9,S,S,S,S,S,19F,*8956,84.89
24,H20175295,i26_04_barcode14,S,S,S,S,S,S,S,NP,8,NaN,NaN,NaN,NaN,NaN,19F,*13c8,83.43
25,T20595649,i27_04_barcode78,S,S,S,S,S,S,S,NP,21,S,S,S,S,S,17F,*8467,86.32
26,H18637568,i28_03_barcode17,I,S,R,S,S,S,S,NP,15,I,S,S,I,R,35B,*f533,99.76
27,H19691888,i29_03_barcode37,I,S,R,S,S,S,S,NP,18,S,S,S,S,I,35D,*dd3b,99.81
28,H18510890,i30_03_barcode58,I,S,S,S,S,S,S,NP,23,S,S,S,S,I,35D,*3fae,91.21
29,M17945178,i31_03_barcode73,NaN,S,R,S,S,S,S,NP,15,S,S,S,S,I,35B,*8f24,92.19
30,F18442395,i32_03_barcode76,I,S,R,S,S,S,S,NP,17,S,S,S,S,I,35D,*2834,95.27
31,M19219775,i33_03_barcode90,I,S,R,S,S,S,S,NP,8,S,S,S,I,R,35D,*dd3b,99.18
32,T17202514,i34_03_barcode33,S,S,R,S,S,S,S,NP,10,S,S,S,S,S,15B,*265d,96.15
33,M17112142,i35_03_barcode41,S,S,S,S,S,S,S,Ear,23,S,S,S,S,S,15C,*4cb3,97.56
34,H17221555,i36_03_barcode49,S,S,S,S,S,S,S,NP,22,S,S,S,S,S,15B,*9952,93.94
35,M18000909,i37_03_barcode09,S,S,R,S,S,S,S,NP,13,S,S,S,S,I,15C,*265d,90.77
36,W18629076,i38_01_barcode36,S,S,S,S,S,S,S,NP,31,S,S,S,S,S,15B,1262,99.87
37,W18265095,i39_01_barcode24,S,S,S,S,S,S,S,NP,8,S,S,S,S,S,23B,36,100.00
38,H18485654,i40_01_barcode37,I,S,S,S,S,S,S,NP,13,S,S,S,S,I,23B,1373,99.99
39,M18587789,i41_01_barcode39,S,S,S,S,S,S,S,NP,11,S,S,S,S,S,23B,36,100.00
40,M18617870,i42_01_barcode40,I,S,S,S,S,S,S,NP,8,S,S,S,S,I,23B,14492,99.99

In [45]:
# export merged file for R plotting
meta_pathogen_merged.to_csv(DIR / OUTPUT_file, index=False)

In [122]:
# after install biopython
# tree process for nanopore
from Bio import Phylo

tree = Phylo.read(DIR / "RAxML_bipartitions.spn_tree", "newick")

for leaf in tree.get_terminals():
    # rename reference
    if leaf.name == "GCF_003003495.1_ASM300349v1_genomic.fna.ref":
        leaf.name = "Reference"
        continue
        
    # set the leafs to the same as Index
    match = re.search(r"pattern", leaf.name)
    if match:
        leaf.name = match.group(1)

Phylo.write(tree, DIR / "RAxML_bipartitions_renamed.spn_tree", "newick")

1

In [15]:
# after install biopython
# tree process for illumina
from Bio import Phylo

tree = Phylo.read(DIR / "RAxML_bipartitions.spn_tree", "newick")

for leaf in tree.get_terminals():
    if leaf.name == "GCF_003003495.1_ASM300349v1_genomic.fna.ref":
        leaf.name = "reference"
    else:
        if leaf.name.startswith("snippy_"):
            leaf.name = leaf.name.removeprefix("snippy_")
        if leaf.name.endswith("_pypolca_corrected.fasta"):
            leaf.name = leaf.name.removesuffix("_pypolca_corrected.fasta")
Phylo.write(tree, DIR / "RAxML_bipartitions_renamed.spn_tree", "newick")

1

In [7]:
tree_ids = {leaf.name for leaf in tree.get_terminals()}
table_ids = set(indexed_metadata["Index"])

print("Missing in metadata:", tree_ids - table_ids)
print("Missing in tree:", table_ids - tree_ids)

NameError: name 'indexed_metadata' is not defined

In [ ]:
select_resist = resistance[["Index", "amx", "croNonMeningitis", "ctxNonMeningitis", "cxm", "mem", "penNonMeningitis", "penNonMeningitis_thresh"]]