In [1]:
import pandas as pd
import glob
import os
import re

In [3]:
nanopore_index = pd.read_excel("../data_file/SPN_nanopore_Nader/Combined_data_for_SPN_nanopore_WGS.xlsx")
map_table = pd.read_excel("../data_file/Look_up_table.xlsx")

nanopore_filename = pd.read_csv("../data_file/barcode.txt", sep="\t", header=None, names=["nanopore_filename"])

In [5]:
nanopore_index

,Genome Name,Genome Length,No. Contigs,Smallest Contig,Largest Contig,Average Contig Length,N50,GC Content,Genome fraction (%),Lineage,...,amoxmic_ear,methomic_pre_ear,methomic_ear,levomic_pre_ear,levomic_ear,dcollect_ear,pcn_sens_ear,accessionNUM_ear,LDX,RDX
0,01_barcode01.contigs,2104635.0,2.0,25169.0,2079466.0,1052317.0,2079466.0,39.7,85.751,3,...,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,AOM,AOM
1,01_barcode03.contigs,2289937.0,6.0,13810.0,1705204.0,381656.0,1705204.0,39.7,88.722,11,...,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,No effusion,No effusion
2,01_barcode05.contigs,2058639.0,2.0,12414.0,2046225.0,1029319.0,2046225.0,39.8,85.137,59,...,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,AOM,No effusion
3,01_barcode09.contigs,2100474.0,2.0,10602.0,2089872.0,1050237.0,2089872.0,39.6,90.040,5,...,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,No effusion,No effusion
4,01_barcode10.contigs,2081348.0,1.0,2081348.0,2081348.0,2081348.0,2081348.0,39.6,86.318,7,...,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,No effusion,No effusion
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122,04_barcode86.contigs,2160830.0,8.0,13053.0,922353.0,270103.0,513729.0,39.7,87.318,36,...,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,AOM,No effusion
123,04_barcode94.contigs,2136584.0,26.0,3102.0,548120.0,82176.0,219604.0,39.6,87.196,Not assigned,...,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,AOM,NaN
124,04_barcode95.contigs,2244725.0,15.0,6288.0,707650.0,149648.0,292058.0,39.8,90.291,5,...,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,OME,AOM
125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN
126,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN

In [7]:
nanopore_filename

                  nanopore_filename
0    Batch1_4.barcode12_33.fastq.gz
1         Batch1.barcode01.fastq.gz
2         Batch1.barcode02.fastq.gz
3         Batch1.barcode03.fastq.gz
4         Batch1.barcode04.fastq.gz
..                              ...
216       Batch4.barcode86.fastq.gz
217       Batch4.barcode87.fastq.gz
218       Batch4.barcode89.fastq.gz
219       Batch4.barcode94.fastq.gz
220       Batch4.barcode95.fastq.gz

[221 rows x 1 columns]

In [9]:
# rename column from nanopore metadata file
nanopore_index = nanopore_index.rename(columns={'accessionNum': 'Accession No', "Genome Name": "Nanopore_index"})
# rename column from illumina metadata file
map_table = map_table.rename(columns={"Our number":"Illumina_index"})

# extract batch and barcode numbers
nanopore_index[['batch', 'barcode']] = nanopore_index['Nanopore_index'].str.extract(r'(\d)_barcode(\d+)')
# build a column that matches nanopore data file name
nanopore_index['fastq_name'] = (
    'Batch' + nanopore_index['batch'] +
    '.barcode' + nanopore_index['barcode'] +
    '.fastq.gz'
)

target1 = map_table[["Accession No", "Illumina_index"]]
target2 = nanopore_index[["Nanopore_index", "fastq_name", "Accession No"]]

In [13]:
nanopore_index[nanopore_index["fastq_name"] == "Batch2.barcode09.fastq.gz"]

,Nanopore_index,Genome Length,No. Contigs,Smallest Contig,Largest Contig,Average Contig Length,N50,GC Content,Genome fraction (%),Lineage,...,levomic_pre_ear,levomic_ear,dcollect_ear,pcn_sens_ear,accessionNUM_ear,LDX,RDX,batch,barcode,fastq_name
35,02_barcode09.contigs,2144936.0,4.0,12937.0,1290325.0,536234.0,1290325.0,39.6,86.576,6,...,=,1.0,2023-03-31,Intermediate,F18448840,AOM,AOM,2,09,Batch2.barcode09.fastq.gz

In [15]:
nanopore_index["Accession No"]
nanopore_index[nanopore_index["Accession No"] == "F18448840"]

,Nanopore_index,Genome Length,No. Contigs,Smallest Contig,Largest Contig,Average Contig Length,N50,GC Content,Genome fraction (%),Lineage,...,levomic_pre_ear,levomic_ear,dcollect_ear,pcn_sens_ear,accessionNUM_ear,LDX,RDX,batch,barcode,fastq_name
35,02_barcode09.contigs,2144936.0,4.0,12937.0,1290325.0,536234.0,1290325.0,39.6,86.576,6,...,=,1.0,2023-03-31,Intermediate,F18448840,AOM,AOM,2,09,Batch2.barcode09.fastq.gz

In [17]:
target2

,Nanopore_index,fastq_name,Accession No
0,01_barcode01.contigs,Batch1.barcode01.fastq.gz,W16709299
1,01_barcode03.contigs,Batch1.barcode03.fastq.gz,W17143487
2,01_barcode05.contigs,Batch1.barcode05.fastq.gz,F16380623
3,01_barcode09.contigs,Batch1.barcode09.fastq.gz,T17601862
4,01_barcode10.contigs,Batch1.barcode10.fastq.gz,F16721574
...,...,...,...
122,04_barcode86.contigs,Batch4.barcode86.fastq.gz,T20596539
123,04_barcode94.contigs,Batch4.barcode94.fastq.gz,W20470375
124,04_barcode95.contigs,Batch4.barcode95.fastq.gz,H20331969
125,NaN,NaN,NaN
126,NaN,NaN,Note: red IDs are the same but were not merged...

In [19]:
merged1 = pd.merge(
    target1,
    target2,
    left_on='Accession No',
    right_on='Accession No',
    how='inner'
)

In [21]:
merged1

,Accession No,Illumina_index,Nanopore_index,fastq_name
0,W15810037,1,02_barcode52.contigs,Batch2.barcode52.fastq.gz
1,W17143487,2,01_barcode03.contigs,Batch1.barcode03.fastq.gz
2,F16380623,3,01_barcode05.contigs,Batch1.barcode05.fastq.gz
3,W17653277,4,01_barcode11.contigs,Batch1.barcode11.fastq.gz
4,M17701635,5,01_barcode12.contigs,Batch1.barcode12.fastq.gz
5,M17701635,5,04_barcode33.contigs,Batch4.barcode33.fastq.gz
6,T18271326,6,02_barcode90.contigs,Batch2.barcode90.fastq.gz
7,M18434558,7,01_barcode34.contigs,Batch1.barcode34.fastq.gz
8,F17654457,8,01_barcode35.contigs,Batch1.barcode35.fastq.gz
9,F17896493,9,03_barcode89.contigs,Batch3.barcode89.fastq.gz
10,F18239423,10,02_barcode11.contigs,Batch2.barcode11.fastq.gz
11,T19376701,11,03_barcode74.contigs,Batch3.barcode74.fastq.gz
12,M19156630,12,02_barcode35.contigs,Batch2.barcode35.fastq.gz
13,T19510623,13,02_barcode17.contigs,Batch2.barcode17.fastq.gz
14,M19257038,14,02_barcode41.contigs,Batch2.barcode41.fastq.gz
15,F18448840,15,02_barcode09.contigs,Batch2.barcode09.fastq.gz
16,F18448806,16,02_barcode57.contigs,Batch2.barcode57.fastq.gz
17,H19271491,17,02_barcode51.contigs,Batch2.barcode51.fastq.gz
18,T19641883,18,03_barcode91.contigs,Batch3.barcode91.fastq.gz
19,H19332824,19,03_barcode20.contigs,Batch3.barcode20.fastq.gz
20,T19860215,20,02_barcode12.contigs,Batch2.barcode12.fastq.gz
21,W19724538,21,02_barcode28.contigs,Batch2.barcode28.fastq.gz
22,W19756047,22,03_barcode13.contigs,Batch3.barcode13.fastq.gz
23,W20312234,23,02_barcode58.contigs,Batch2.barcode58.fastq.gz
24,M20130536,24,02_barcode74.contigs,Batch2.barcode74.fastq.gz
25,H20143631,25,04_barcode53.contigs,Batch4.barcode53.fastq.gz
26,H20175295,26,04_barcode14.contigs,Batch4.barcode14.fastq.gz
27,T20595649,27,04_barcode78.contigs,Batch4.barcode78.fastq.gz
28,H18637568,28,03_barcode17.contigs,Batch3.barcode17.fastq.gz
29,H19691888,29,03_barcode37.contigs,Batch3.barcode37.fastq.gz
30,H18510890,30,03_barcode58.contigs,Batch3.barcode58.fastq.gz
31,M17945178,31,03_barcode73.contigs,Batch3.barcode73.fastq.gz
32,F18442395,32,03_barcode76.contigs,Batch3.barcode76.fastq.gz
33,M19219775,33,03_barcode90.contigs,Batch3.barcode90.fastq.gz
34,T17202514,34,03_barcode33.contigs,Batch3.barcode33.fastq.gz
35,M17112142,35,03_barcode41.contigs,Batch3.barcode41.fastq.gz
36,H17221555,36,03_barcode49.contigs,Batch3.barcode49.fastq.gz
37,M18000909,37,03_barcode09.contigs,Batch3.barcode09.fastq.gz
38,W18629076,38,01_barcode36.contigs,Batch1.barcode36.fastq.gz
39,W18265095,39,01_barcode24.contigs,Batch1.barcode24.fastq.gz
40,H18485654,40,01_barcode37.contigs,Batch1.barcode37.fastq.gz
41,M18587789,41,01_barcode39.contigs,Batch1.barcode39.fastq.gz
42,M18617870,42,01_barcode40.contigs,Batch1.barcode40.fastq.gz
43,H19207745,43,02_barcode33.contigs,Batch2.barcode33.fastq.gz

In [23]:
merged2 = pd.merge(
    merged1,
    nanopore_filename,
    left_on='fastq_name',
    right_on='nanopore_filename',
    how='left'
)

In [25]:
merged2

,Accession No,Illumina_index,Nanopore_index,fastq_name,nanopore_filename
0,W15810037,1,02_barcode52.contigs,Batch2.barcode52.fastq.gz,Batch2.barcode52.fastq.gz
1,W17143487,2,01_barcode03.contigs,Batch1.barcode03.fastq.gz,Batch1.barcode03.fastq.gz
2,F16380623,3,01_barcode05.contigs,Batch1.barcode05.fastq.gz,Batch1.barcode05.fastq.gz
3,W17653277,4,01_barcode11.contigs,Batch1.barcode11.fastq.gz,Batch1.barcode11.fastq.gz
4,M17701635,5,01_barcode12.contigs,Batch1.barcode12.fastq.gz,NaN
5,M17701635,5,04_barcode33.contigs,Batch4.barcode33.fastq.gz,NaN
6,T18271326,6,02_barcode90.contigs,Batch2.barcode90.fastq.gz,Batch2.barcode90.fastq.gz
7,M18434558,7,01_barcode34.contigs,Batch1.barcode34.fastq.gz,Batch1.barcode34.fastq.gz
8,F17654457,8,01_barcode35.contigs,Batch1.barcode35.fastq.gz,Batch1.barcode35.fastq.gz
9,F17896493,9,03_barcode89.contigs,Batch3.barcode89.fastq.gz,Batch3.barcode89.fastq.gz
10,F18239423,10,02_barcode11.contigs,Batch2.barcode11.fastq.gz,Batch2.barcode11.fastq.gz
11,T19376701,11,03_barcode74.contigs,Batch3.barcode74.fastq.gz,Batch3.barcode74.fastq.gz
12,M19156630,12,02_barcode35.contigs,Batch2.barcode35.fastq.gz,Batch2.barcode35.fastq.gz
13,T19510623,13,02_barcode17.contigs,Batch2.barcode17.fastq.gz,Batch2.barcode17.fastq.gz
14,M19257038,14,02_barcode41.contigs,Batch2.barcode41.fastq.gz,Batch2.barcode41.fastq.gz
15,F18448840,15,02_barcode09.contigs,Batch2.barcode09.fastq.gz,Batch2.barcode09.fastq.gz
16,F18448806,16,02_barcode57.contigs,Batch2.barcode57.fastq.gz,Batch2.barcode57.fastq.gz
17,H19271491,17,02_barcode51.contigs,Batch2.barcode51.fastq.gz,Batch2.barcode51.fastq.gz
18,T19641883,18,03_barcode91.contigs,Batch3.barcode91.fastq.gz,Batch3.barcode91.fastq.gz
19,H19332824,19,03_barcode20.contigs,Batch3.barcode20.fastq.gz,Batch3.barcode20.fastq.gz
20,T19860215,20,02_barcode12.contigs,Batch2.barcode12.fastq.gz,Batch2.barcode12.fastq.gz
21,W19724538,21,02_barcode28.contigs,Batch2.barcode28.fastq.gz,Batch2.barcode28.fastq.gz
22,W19756047,22,03_barcode13.contigs,Batch3.barcode13.fastq.gz,Batch3.barcode13.fastq.gz
23,W20312234,23,02_barcode58.contigs,Batch2.barcode58.fastq.gz,Batch2.barcode58.fastq.gz
24,M20130536,24,02_barcode74.contigs,Batch2.barcode74.fastq.gz,Batch2.barcode74.fastq.gz
25,H20143631,25,04_barcode53.contigs,Batch4.barcode53.fastq.gz,Batch4.barcode53.fastq.gz
26,H20175295,26,04_barcode14.contigs,Batch4.barcode14.fastq.gz,Batch4.barcode14.fastq.gz
27,T20595649,27,04_barcode78.contigs,Batch4.barcode78.fastq.gz,Batch4.barcode78.fastq.gz
28,H18637568,28,03_barcode17.contigs,Batch3.barcode17.fastq.gz,Batch3.barcode17.fastq.gz
29,H19691888,29,03_barcode37.contigs,Batch3.barcode37.fastq.gz,Batch3.barcode37.fastq.gz
30,H18510890,30,03_barcode58.contigs,Batch3.barcode58.fastq.gz,Batch3.barcode58.fastq.gz
31,M17945178,31,03_barcode73.contigs,Batch3.barcode73.fastq.gz,Batch3.barcode73.fastq.gz
32,F18442395,32,03_barcode76.contigs,Batch3.barcode76.fastq.gz,Batch3.barcode76.fastq.gz
33,M19219775,33,03_barcode90.contigs,Batch3.barcode90.fastq.gz,Batch3.barcode90.fastq.gz
34,T17202514,34,03_barcode33.contigs,Batch3.barcode33.fastq.gz,Batch3.barcode33.fastq.gz
35,M17112142,35,03_barcode41.contigs,Batch3.barcode41.fastq.gz,Batch3.barcode41.fastq.gz
36,H17221555,36,03_barcode49.contigs,Batch3.barcode49.fastq.gz,Batch3.barcode49.fastq.gz
37,M18000909,37,03_barcode09.contigs,Batch3.barcode09.fastq.gz,Batch3.barcode09.fastq.gz
38,W18629076,38,01_barcode36.contigs,Batch1.barcode36.fastq.gz,Batch1.barcode36.fastq.gz
39,W18265095,39,01_barcode24.contigs,Batch1.barcode24.fastq.gz,Batch1.barcode24.fastq.gz
40,H18485654,40,01_barcode37.contigs,Batch1.barcode37.fastq.gz,Batch1.barcode37.fastq.gz
41,M18587789,41,01_barcode39.contigs,Batch1.barcode39.fastq.gz,Batch1.barcode39.fastq.gz
42,M18617870,42,01_barcode40.contigs,Batch1.barcode40.fastq.gz,Batch1.barcode40.fastq.gz
43,H19207745,43,02_barcode33.contigs,Batch2.barcode33.fastq.gz,Batch2.barcode33.fastq.gz

In [27]:
merged2["illumina"] = (
    "i"
    + merged2["Illumina_index"].astype(str)
    + "_"
    + merged2["Nanopore_index"].str.replace(".contigs", "", regex=False)
    + "_illumina.fastq.gz"
)

merged2["nanopore"] = (
    "i"
    + merged2["Illumina_index"].astype(str)
    + "_"
    + merged2["Nanopore_index"].str.replace(".contigs", "", regex=False)
    + "_nanopore.fastq.gz"
)

In [29]:
merged2

,Accession No,Illumina_index,Nanopore_index,fastq_name,nanopore_filename,illumina,nanopore
0,W15810037,1,02_barcode52.contigs,Batch2.barcode52.fastq.gz,Batch2.barcode52.fastq.gz,i1_02_barcode52_illumina.fastq.gz,i1_02_barcode52_nanopore.fastq.gz
1,W17143487,2,01_barcode03.contigs,Batch1.barcode03.fastq.gz,Batch1.barcode03.fastq.gz,i2_01_barcode03_illumina.fastq.gz,i2_01_barcode03_nanopore.fastq.gz
2,F16380623,3,01_barcode05.contigs,Batch1.barcode05.fastq.gz,Batch1.barcode05.fastq.gz,i3_01_barcode05_illumina.fastq.gz,i3_01_barcode05_nanopore.fastq.gz
3,W17653277,4,01_barcode11.contigs,Batch1.barcode11.fastq.gz,Batch1.barcode11.fastq.gz,i4_01_barcode11_illumina.fastq.gz,i4_01_barcode11_nanopore.fastq.gz
4,M17701635,5,01_barcode12.contigs,Batch1.barcode12.fastq.gz,NaN,i5_01_barcode12_illumina.fastq.gz,i5_01_barcode12_nanopore.fastq.gz
5,M17701635,5,04_barcode33.contigs,Batch4.barcode33.fastq.gz,NaN,i5_04_barcode33_illumina.fastq.gz,i5_04_barcode33_nanopore.fastq.gz
6,T18271326,6,02_barcode90.contigs,Batch2.barcode90.fastq.gz,Batch2.barcode90.fastq.gz,i6_02_barcode90_illumina.fastq.gz,i6_02_barcode90_nanopore.fastq.gz
7,M18434558,7,01_barcode34.contigs,Batch1.barcode34.fastq.gz,Batch1.barcode34.fastq.gz,i7_01_barcode34_illumina.fastq.gz,i7_01_barcode34_nanopore.fastq.gz
8,F17654457,8,01_barcode35.contigs,Batch1.barcode35.fastq.gz,Batch1.barcode35.fastq.gz,i8_01_barcode35_illumina.fastq.gz,i8_01_barcode35_nanopore.fastq.gz
9,F17896493,9,03_barcode89.contigs,Batch3.barcode89.fastq.gz,Batch3.barcode89.fastq.gz,i9_03_barcode89_illumina.fastq.gz,i9_03_barcode89_nanopore.fastq.gz
10,F18239423,10,02_barcode11.contigs,Batch2.barcode11.fastq.gz,Batch2.barcode11.fastq.gz,i10_02_barcode11_illumina.fastq.gz,i10_02_barcode11_nanopore.fastq.gz
11,T19376701,11,03_barcode74.contigs,Batch3.barcode74.fastq.gz,Batch3.barcode74.fastq.gz,i11_03_barcode74_illumina.fastq.gz,i11_03_barcode74_nanopore.fastq.gz
12,M19156630,12,02_barcode35.contigs,Batch2.barcode35.fastq.gz,Batch2.barcode35.fastq.gz,i12_02_barcode35_illumina.fastq.gz,i12_02_barcode35_nanopore.fastq.gz
13,T19510623,13,02_barcode17.contigs,Batch2.barcode17.fastq.gz,Batch2.barcode17.fastq.gz,i13_02_barcode17_illumina.fastq.gz,i13_02_barcode17_nanopore.fastq.gz
14,M19257038,14,02_barcode41.contigs,Batch2.barcode41.fastq.gz,Batch2.barcode41.fastq.gz,i14_02_barcode41_illumina.fastq.gz,i14_02_barcode41_nanopore.fastq.gz
15,F18448840,15,02_barcode09.contigs,Batch2.barcode09.fastq.gz,Batch2.barcode09.fastq.gz,i15_02_barcode09_illumina.fastq.gz,i15_02_barcode09_nanopore.fastq.gz
16,F18448806,16,02_barcode57.contigs,Batch2.barcode57.fastq.gz,Batch2.barcode57.fastq.gz,i16_02_barcode57_illumina.fastq.gz,i16_02_barcode57_nanopore.fastq.gz
17,H19271491,17,02_barcode51.contigs,Batch2.barcode51.fastq.gz,Batch2.barcode51.fastq.gz,i17_02_barcode51_illumina.fastq.gz,i17_02_barcode51_nanopore.fastq.gz
18,T19641883,18,03_barcode91.contigs,Batch3.barcode91.fastq.gz,Batch3.barcode91.fastq.gz,i18_03_barcode91_illumina.fastq.gz,i18_03_barcode91_nanopore.fastq.gz
19,H19332824,19,03_barcode20.contigs,Batch3.barcode20.fastq.gz,Batch3.barcode20.fastq.gz,i19_03_barcode20_illumina.fastq.gz,i19_03_barcode20_nanopore.fastq.gz
20,T19860215,20,02_barcode12.contigs,Batch2.barcode12.fastq.gz,Batch2.barcode12.fastq.gz,i20_02_barcode12_illumina.fastq.gz,i20_02_barcode12_nanopore.fastq.gz
21,W19724538,21,02_barcode28.contigs,Batch2.barcode28.fastq.gz,Batch2.barcode28.fastq.gz,i21_02_barcode28_illumina.fastq.gz,i21_02_barcode28_nanopore.fastq.gz
22,W19756047,22,03_barcode13.contigs,Batch3.barcode13.fastq.gz,Batch3.barcode13.fastq.gz,i22_03_barcode13_illumina.fastq.gz,i22_03_barcode13_nanopore.fastq.gz
23,W20312234,23,02_barcode58.contigs,Batch2.barcode58.fastq.gz,Batch2.barcode58.fastq.gz,i23_02_barcode58_illumina.fastq.gz,i23_02_barcode58_nanopore.fastq.gz
24,M20130536,24,02_barcode74.contigs,Batch2.barcode74.fastq.gz,Batch2.barcode74.fastq.gz,i24_02_barcode74_illumina.fastq.gz,i24_02_barcode74_nanopore.fastq.gz
25,H20143631,25,04_barcode53.contigs,Batch4.barcode53.fastq.gz,Batch4.barcode53.fastq.gz,i25_04_barcode53_illumina.fastq.gz,i25_04_barcode53_nanopore.fastq.gz
26,H20175295,26,04_barcode14.contigs,Batch4.barcode14.fastq.gz,Batch4.barcode14.fastq.gz,i26_04_barcode14_illumina.fastq.gz,i26_04_barcode14_nanopore.fastq.gz
27,T20595649,27,04_barcode78.contigs,Batch4.barcode78.fastq.gz,Batch4.barcode78.fastq.gz,i27_04_barcode78_illumina.fastq.gz,i27_04_barcode78_nanopore.fastq.gz
28,H18637568,28,03_barcode17.contigs,Batch3.barcode17.fastq.gz,Batch3.barcode17.fastq.gz,i28_03_barcode17_illumina.fastq.gz,i28_03_barcode17_nanopore.fastq.gz
29,H19691888,29,03_barcode37.contigs,Batch3.barcode37.fastq.gz,Batch3.barcode37.fastq.gz,i29_03_barcode37_illumina.fastq.gz,i29_03_barcode37_nanopore.fastq.gz
30,H18510890,30,03_barcode58.contigs,Batch3.barcode58.fastq.gz,Batch3.barcode58.fastq.gz,i30_03_barcode58_illumina.fastq.gz,i30_03_barcode58_nanopore.fastq.gz
31,M17945178,31,03_barcode73.contigs,Batch3.barcode73.fastq.gz,Batch3.barcode73.fastq.gz,i31_03_barcode73_illumina.fastq.gz,i31_03_barcode73_nanopore.fastq.gz
32,F18442395,32,03_barcode76.contigs,Batch3.barcode76.fastq.gz,Batch3.barcode76.fastq.gz,i32_03_barcode76_illumina.fastq.gz,i32_03_barcode76_nanopore.fastq.gz
33,M19219775,33,03_barcode90.contigs,Batch3.barcode90.fastq.gz,Batch3.barcode90.fastq.gz,i33_03_barcode90_illumina.fastq.gz,i33_03_barcode90_nanopore.fastq.gz
34,T17202514,34,03_barcode33.contigs,Batch3.barcode33.fastq.gz,Batch3.barcode33.fastq.gz,i34_03_barcode33_illumina.fastq.gz,i34_03_barcode33_nanopore.fastq.gz
35,M17112142,35,03_barcode41.contigs,Batch3.barcode41.fastq.gz,Batch3.barcode41.fastq.gz,i35_03_barcode41_illumina.fastq.gz,i35_03_barcode41_nanopore.fastq.gz
36,H17221555,36,03_barcode49.contigs,Batch3.barcode49.fastq.gz,Batch3.barcode49.fastq.gz,i36_03_barcode49_illumina.fastq.gz,i36_03_barcode49_nanopore.fastq.gz
37,M18000909,37,03_barcode09.contigs,Batch3.barcode09.fastq.gz,Batch3.barcode09.fastq.gz,i37_03_barcode09_illumina.fastq.gz,i37_03_barcode09_nanopore.fastq.gz
38,W18629076,38,01_barcode36.contigs,Batch1.barcode36.fastq.gz,Batch1.barcode36.fastq.gz,i38_01_barcode36_illumina.fastq.gz,i38_01_barcode36_nanopore.fastq.gz
39,W18265095,39,01_barcode24.contigs,Batch1.barcode24.fastq.gz,Batch1.barcode24.fastq.gz,i39_01_barcode24_illumina.fastq.gz,i39_01_barcode24_nanopore.fastq.gz
40,H18485654,40,01_barcode37.contigs,Batch1.barcode37.fastq.gz,Batch1.barcode37.fastq.gz,i40_01_barcode37_illumina.fastq.gz,i40_01_barcode37_nanopore.fastq.gz
41,M18587789,41,01_barcode39.contigs,Batch1.barcode39.fastq.gz,Batch1.barcode39.fastq.gz,i41_01_barcode39_illumina.fastq.gz,i41_01_barcode39_nanopore.fastq.gz
42,M18617870,42,01_barcode40.contigs,Batch1.barcode40.fastq.gz,Batch1.barcode40.fastq.gz,i42_01_barcode40_illumina.fastq.gz,i42_01_barcode40_nanopore.fastq.gz
43,H19207745,43,02_barcode33.contigs,Batch2.barcode33.fastq.gz,Batch2.barcode33.fastq.gz,i43_02_barcode33_illumina.fastq.gz,i43_02_barcode33_nanopore.fastq.gz

In [31]:
merged2.to_csv("../data_file/illumina_nanopore_mapping.csv", index=False)

In [35]:
merged2.to_excel("../data_file/illumina_nanopore_mapping.xlsx", index=False)

In [ ]:
# illumina: ix_nx_bx_illumina.fastq.gz
# ex: Batch2.barcode90.fastq.gz with illumina index 6 -> i6_n2_b90_illumina.fastq.gz
# nanopore: ix_nx_bx_nanopore.fastq.gz
# ex: i6_n2_b90_nanopore.fastq.gz